services:
  - name: traefik
    enabled: true
    traefik:
      enabled: true
      rules:
        - host: traefik.${TRAEFIK_DOMAIN}
          service: api@internal
          httpAuth: true
  - name: deluge
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: deluge.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 8112
          # Uncomment to specify custom schme (http by default)
          # internalScheme: http
          # Uncomment to *NOT* generate LetsEncrypt certificate (useful for local domains)
          # httpOnly: true
  - name: flood
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: flood.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 3000
  - name: qbittorrent
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: qbittorrent.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 8080
  - name: plex
    enabled: true
    vpn: false
    # uncomment to use custom file with specific parameters for hardware transcoding
    # customFile: plex-hardware-transcoding.yaml
    # You can also place you own file in services/custom/ and call it here like this:
    # customFile: custom/my_own_file.yaml
    traefik:
      enabled: true
      rules:
        - host: plex.${TRAEFIK_DOMAIN}
          httpAuth: false
          internalPort: 32400
  - name: flaresolverr
    enabled: true
    vpn: false
    traefik:
      enabled: false
      rules: []
  - name: jackett
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: jackett.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 9117
  - name: prowlarr
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: prowlarr.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 9696
  - name: sonarr
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: sonarr.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 8989
  - name: radarr
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: radarr.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 7878
  - name: bazarr
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: bazarr.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 6767
  - name: lidarr
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: lidarr.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 8686
  - name: readarr
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: readarr.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 8787
  - name: calibre
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: calibre-admin.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 8080
  - name: calibre-web
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: calibre.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 8083
  - name: komga
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: komga.${TRAEFIK_DOMAIN}
          httpAuth: false
          internalPort: 8080
  - name: kavita
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: kavita.${TRAEFIK_DOMAIN}
          httpAuth: false
          internalPort: 5000
  - name: ombi
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: ombi.${TRAEFIK_DOMAIN}
          httpAuth: false
          internalPort: 3579
  - name: overseerr
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: overseerr.${TRAEFIK_DOMAIN}
          httpAuth: false
          internalPort: 5055
  - name: tautulli
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: tautulli.${TRAEFIK_DOMAIN}
          httpAuth: false
          internalPort: 8181
  - name: ntfy
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: ntfy.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 2586
  - name: jdownloader
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: jdownloader.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 5800
  - name: tdarr
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: tdarr.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 8265
  - name: nextcloud
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: nextcloud.${TRAEFIK_DOMAIN}
          httpAuth: false
          internalPort: 443
          internalScheme: https
  - name: paperless
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: paperless.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 8000
  - name: portainer
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: portainer.${TRAEFIK_DOMAIN}
          httpAuth: false
          internalPort: 9000
  - name: netdata
    enabled: true
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: netdata.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 19999
  - name: duplicati
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: duplicati.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 8200
  - name: syncthing
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: syncthing.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 8384
  - name: heimdall
    # Beware to the host when enabling it!
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: ${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 80
  - name: homarr
    enabled: false
    vpn: false
    traefik:
      enabled: true
      rules:
        - host: homarr.${TRAEFIK_DOMAIN}
          httpAuth: true
          internalPort: 7575
  # Gluetun is the VPN client service.
  - name: gluetun
    enabled: false
    traefik:
      enabled: false
      rules: []
