version: '2'

networks:
    main:

volumes:
    config:
        driver: local
    torrents:
        driver: local

services:
    frontend:
        image: kelvinchen/seedbox:frontend
        build: Dockerfiles/frontend
        restart: always
        networks:
            - main
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - config:/config
        env_file:
            - config

    rtorrent:
        image: kelvinchen/seedbox:rtorrent
        build: Dockerfiles/rtorrent
        restart: always
        networks:
            - main
        ports:
            - "49161:49161"
            - "49161:49161/udp"
            - "6881:6881/udp"
        volumes:
            - config:/config
            - torrents:/torrents

    plex:
        image: kelvinchen/seedbox:plex
        build: Dockerfiles/plex
        restart: always
        networks:
            - main
        ports:
            - "32400:32400"
        volumes:
            - config:/config
            - torrents:/torrents
        env_file:
            - config

    sickrage:
        image: kelvinchen/seedbox:sickrage
        build: Dockerfiles/sickrage
        restart: always
        networks:
            - main
        volumes:
            - config:/config
            - torrents:/torrents

    sonarr:
        image: kelvinchen/seedbox:sonarr
        build: Dockerfiles/sonarr
        restart: always
        networks:
            - main
        volumes:
            - config:/config
            - torrents:/torrents

    syncthing:
        image: kelvinchen/seedbox:syncthing
        build: Dockerfiles/syncthing
        restart: always
        networks:
            - main
        ports:
            - "22000:22000"
            - "21027:21027/udp"
        volumes:
            - config:/config
            - torrents:/torrents

    openvpn:
        image: kelvinchen/seedbox:openvpn
        build: Dockerfiles/openvpn
        restart: always
        networks:
            - main
        ports:
            - "1194:1194/udp"
        volumes:
            - config:/config
            - torrents:/torrents
        cap_add:
            - NET_ADMIN
